sudo: required
dist: trusty
language: cpp

cache:
  directories:
    - $HOME/.conan

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - clang-3.8
      - cmake
      - cmake-data

compiler:
  - gcc

os:
  - linux

env:
  - build_type=release options="-D stlab_testing=ON"

branches:
  except: /pr\/.*/
  
before_install:
  - export PATH=$HOME/.local.bin:$PATH
  - pip install --user $(whoami) conan
  
script:
  - .travis/build.sh
