sudo: required
dist: trusty
language: cpp

cache:
  directories:
    - $HOME/.conan

addons:
  apt:
    sources:
      - sourceline: "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.8 main"
        key_url : "http://apt.llvm.org/llvm-snapshot.gpg.key"
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-5
      - clang-3.8
      - cmake
      - cmake-data

compiler:
  - gcc

os:
  - linux

env:
  - build_type=release options="-D stlab_testing=ON"

branches:
  except: /pr\/.*/
  
before_install:
  - pip install conan
  
script:
  - .travis/build.sh
